---
layout: default
title: Selamat Datang
---

# Halo, saya Chincan787

Selamat datang di website pribadi saya.  
Saya sedang membangun berbagai proyek menarik di GitHub.

- **GitHub**: [@chincan787](https://github.com/chincan787)
- **Email**: contoh@email.com

Baca [blog saya](./blog) untuk info terbaru.
