title: GenAI Sui Wallet
description: An AI-powered Web3 wallet built on the Sui blockchain
baseurl: "" # leave this empty for user or organization sites (e.g. chincan787.github.io)
url: "https://chincan787.github.io" # replace with your GitHub Pages URL

theme: minima # optional, only if you're using a default theme

plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
